### ISSUE TITLE
Can you support *.feature files too? 

### ISSUE THREAD

**Issue by mrj04** [asterium/IdeaJbehaveStepGenerationPlugin#4]
step in *.feature file to generate and jump to step definitions.

**Comment by asterium** [comment]
I think yes, I can add this feature.
As per roadmap, first milestone would be generation of step definitions into java classes (to be selected at the moment of generation). After that jumping to the generated code should not be a problem

**Comment by asterium** [comment]
@mrj04 Please check version of the plugin 1.2.0
Published today
